version: '3.9'

services:
  # NodeJS Service
  api:
    image: ${SERVICE_DOCKER_IMAGE_NAME}
    build: .
    container_name: ${SERVICE_DOCKER_CONTAINER_NAME}
    ports:
      - ${SERVICE_HOST_PORT}:${SERVICE_CONTAINER_PORT}
    volumes:
      - ${SERVICE_HOST_VOLUME_FOLDER_INPUT}:${SERVICE_DOCKER_CONTAINER_WORKING_DIRECTORY}/node-microservice-input
      - ${SERVICE_HOST_VOLUME_FOLDER_OUTPUT}:${SERVICE_DOCKER_CONTAINER_WORKING_DIRECTORY}/node-microservice-output
      - ${SERVICE_HOST_VOLUME_FOLDER_CONFIG}:${SERVICE_DOCKER_CONTAINER_WORKING_DIRECTORY}/node-microservice-output
      - ${SERVICE_HOST_VOLUME_FOLDER_LOG}:${SERVICE_DOCKER_CONTAINER_WORKING_DIRECTORY}/node-microservice-output